server:
  port: 8080

spring:
  application:
    name: kyc-service


jwt :
  access :
    key : eionflakenflkasnionewaf
    validTime : 604800000 #7?

json:
  path:
    members: json/members.json

uri:
  stream: http://localhost:5050
