server:
  port: 8080

spring:
  application:
    name: kyc-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  logging.level:
    org.hibernate.SQL: debug


jwt :
  access :
    key : eionflakenflkasnionewaf
    validTime : 604800000 #7?

json:
  path:
    members: json/members.json

uri:
  stream: http://localhost:5001
